/-
Copyright (c) 2025 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne, Paulo Rauber
-/
module

public import LeanMachineLearning.ForMathlib.MeasureTheory.Measurable
public import LeanMachineLearning.ForMathlib.Probability.Kernel.IonescuTulcea.Traj

/-!
# Algorithms and environments

We define structures for stochastic, sequential algorithms and environments, and the notion of an
algorithm-environment sequence, which is a sequence of actions and feedbacks generated by
an algorithm interacting with an environment.

At time `n`, the algorithm has observed the `n` action-feedback pairs at times `0, ..., n - 1`.
That history is an element of `Fin n → 𝓐 × 𝓨`. The algorithm then chooses an action `A n`
according to its policy, and the environment returns a feedback `Y n` given the history and `A n`.
In particular, the first action is chosen according to the policy at time `0`, applied to the
empty history (the unique element of `Fin 0 → 𝓐 × 𝓨`).

## Main definitions

* `Algorithm 𝓐 𝓨`: a stochastic, sequential algorithm.
* `Environment 𝓐 𝓨`: a stochastic environment.
* `history A Y n`: the history before time `n`, a random variable with values in `Fin n → 𝓐 × 𝓨`.
* `IsAlgEnvSeq A 𝓨 alg env P`: an algorithm-environment sequence. That is, a sequence of
  actions `A` and feedback `Y` that have the correct conditional distributions to be generated by
  an algorithm `alg` interacting with an environment `env`, defined on a probability space `(Ω, P)`.
* `IsAlgEnvSeqUntil A Y alg env P N`: `A` and `Y` form an algorithm-environment sequence for the
  times `n < N`.
* `prod_left alg`: an `Algorithm 𝓐 (𝓧 × 𝓨)` obtained from an algorithm `alg : Algorithm 𝓐 𝓨` by
  ignoring the `𝓧` component of each observation.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Filter Real Finset

open scoped ENNReal NNReal

namespace Learning

variable {𝓐 𝓨 Ω : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- A stochastic, sequential algorithm. -/
structure Algorithm (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] where
  /-- Policy or sampling rule: distribution of the action at time `n` given the history of the
  `n` previous action-feedback pairs. -/
  policy : (n : ℕ) → Kernel (Fin n → 𝓐 × 𝓨) 𝓐
  /-- The policy is a Markov kernel. -/
  [h_policy : ∀ n, IsMarkovKernel (policy n)]

instance (alg : Algorithm 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) := alg.h_policy n

/-- Distribution of the first action: the policy at time `0` applied to the empty history. -/
def Algorithm.p0 (alg : Algorithm 𝓐 𝓨) : Measure 𝓐 :=
  alg.policy 0 default
deriving IsProbabilityMeasure

lemma Algorithm.p0_def (alg : Algorithm 𝓐 𝓨) : alg.p0 = alg.policy 0 default := rfl

lemma Algorithm.policy_zero (alg : Algorithm 𝓐 𝓨) (h : Fin 0 → 𝓐 × 𝓨) :
    alg.policy 0 h = alg.p0 := by
  rw [Unique.eq_default h]
  rfl

/-- An algorithm with observations in `𝓧 × 𝓨` obtained from an algorithm with observations in `𝓨`
by ignoring the `𝓧` component of each observation. -/
@[simps]
def Algorithm.prodLeft (𝓧 : Type*) [MeasurableSpace 𝓧] (alg : Algorithm 𝓐 𝓨) :
    Algorithm 𝓐 (𝓧 × 𝓨) where
  policy n := (alg.policy n).comap (fun h i ↦ ((h i).1, (h i).2.2)) (by fun_prop)

@[simp]
lemma Algorithm.prodLeft_p0 (𝓧 : Type*) [MeasurableSpace 𝓧] (alg : Algorithm 𝓐 𝓨) :
    (alg.prodLeft 𝓧).p0 = alg.p0 := by
  rw [p0_def, prodLeft_policy, Kernel.comap_apply, policy_zero]

/-- A stochastic environment. -/
structure Environment (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] where
  /-- Distribution of the feedback at time `n` as function of the history of the `n` previous
  action-feedback pairs and of the action at time `n`. -/
  feedback : (n : ℕ) → Kernel ((Fin n → 𝓐 × 𝓨) × 𝓐) 𝓨
  /-- The feedback kernels are Markov kernels. -/
  [h_feedback : ∀ n, IsMarkovKernel (feedback n)]

instance (env : Environment 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) := env.h_feedback n

/-- Distribution of the first feedback given the first action: the feedback kernel at time `0`
applied to the empty history. -/
noncomputable def Environment.ν0 (env : Environment 𝓐 𝓨) : Kernel 𝓐 𝓨 :=
  (env.feedback 0).sectR default
deriving IsMarkovKernel

lemma Environment.ν0_def (env : Environment 𝓐 𝓨) : env.ν0 = (env.feedback 0).sectR default := rfl

lemma Environment.ν0_apply (env : Environment 𝓐 𝓨) (a : 𝓐) :
    env.ν0 a = env.feedback 0 (default, a) := rfl

lemma Environment.feedback_zero (env : Environment 𝓐 𝓨) (h : Fin 0 → 𝓐 × 𝓨) (a : 𝓐) :
    env.feedback 0 (h, a) = env.ν0 a := by
  rw [Unique.eq_default h]
  rfl

/-- Kernel describing the distribution of the action-feedback pair at time `n` given the history
before `n`. -/
noncomputable
def stepKernel (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    Kernel (Fin n → 𝓐 × 𝓨) (𝓐 × 𝓨) :=
  alg.policy n ⊗ₖ env.feedback n
deriving IsMarkovKernel

lemma stepKernel_def (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    stepKernel alg env n = alg.policy n ⊗ₖ env.feedback n := rfl

@[simp]
lemma fst_stepKernel (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    (stepKernel alg env n).fst = alg.policy n := by
  rw [stepKernel, Kernel.fst_compProd]

lemma stepKernel_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (h : Fin 0 → 𝓐 × 𝓨) :
    stepKernel alg env 0 h = alg.p0 ⊗ₘ env.ν0 := by
  rw [Unique.eq_default h, stepKernel, Kernel.compProd_apply_eq_compProd_sectR]
  rfl

section IsAlgEnvSeq

variable {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- Step of the algorithm-environment sequence: the action-feedback pair at time `n`. -/
def step (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : 𝓐 × 𝓨 :=
  (A n ω, Y n ω)

@[fun_prop]
lemma measurable_step (n : ℕ) (hA : Measurable (A n)) (hY : Measurable (Y n)) :
    Measurable (step A Y n) := by
  unfold step
  fun_prop

/-- A random variable that gives the sequence of action-feedback pairs. -/
def trajectory (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (ω : Ω) : ℕ → 𝓐 × 𝓨 := fun n ↦ (A n ω, Y n ω)

@[fun_prop]
lemma measurable_trajectory {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} (hA : ∀ n, Measurable (A n))
    (hR : ∀ n, Measurable (Y n)) : Measurable (trajectory A Y) := by
  unfold trajectory
  fun_prop

/-- History of the algorithm-environment sequence before time `n`: the action-feedback pairs at
times `0, ..., n - 1`. -/
def history (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Fin n → 𝓐 × 𝓨 :=
  fun i ↦ (A i ω, Y i ω)

lemma history_apply (n : ℕ) (ω : Ω) (i : Fin n) : history A Y n ω i = (A i ω, Y i ω) := rfl

@[simp]
lemma history_zero : history A Y 0 = fun _ ↦ (default : Fin 0 → 𝓐 × 𝓨) := Unique.eq_default _

@[fun_prop]
lemma measurable_history (hA : ∀ n, Measurable (A n))
    (hY : ∀ n, Measurable (Y n)) (n : ℕ) :
    Measurable (history A Y n) := by
  unfold history
  fun_prop

lemma eval_comp_history (n : ℕ) :
    (fun x ↦ x (Fin.last n)) ∘ (history A Y (n + 1)) = step A Y n := rfl

lemma fst_eval_comp_history (n : ℕ) :
    (fun x ↦ (x (Fin.last n)).1) ∘ (history A Y (n + 1)) = A n := rfl

lemma snd_eval_comp_history (n : ℕ) :
    (fun x ↦ (x (Fin.last n)).2) ∘ (history A Y (n + 1)) = Y n := rfl

/-- The history before time `m` is a restriction of the history before time `n ≥ m`. -/
lemma history_eq_comp_history {m n : ℕ} (hmn : m ≤ n) :
    history A Y m = (fun h (i : Fin m) ↦ h (Fin.castLE hmn i)) ∘ history A Y n := rfl

lemma history_succ (n : ℕ) :
    history A Y (n + 1) =
      (MeasurableEquiv.finSuccProd (𝓐 × 𝓨) n).symm ∘
        (fun ω ↦ (history A Y n ω, step A Y n ω)) := by
  funext ω
  simp only [Function.comp_apply, MeasurableEquiv.finSuccProd_symm_apply]
  funext i
  refine Fin.lastCases ?_ (fun i ↦ ?_) i
  · simp [history, step]
  · simp [history]

/-- An algorithm-environment sequence: a sequence of actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The action at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (history A Y n) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history and
  the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ (history A Y n ω, A n ω)) (env.feedback n) P

/-- An algorithm-environment sequence until time `N`: a sequence of actions and feedbacks such that
the actions and feedbacks at times `n < N` are generated by an algorithm interacting with
an environment. In particular, the law of `history A Y N` is determined. -/
structure IsAlgEnvSeqUntil
    (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] (N : ℕ) : Prop where
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The action at time `n < N` has the correct conditional distribution given the history. -/
  hasCondDistrib_action n (hn : n < N) :
    HasCondDistrib (A n) (history A Y n) (alg.policy n) P
  /-- The feedback at time `n < N` has the correct conditional distribution given the history and
  the action at time `n`. -/
  hasCondDistrib_feedback n (hn : n < N) :
    HasCondDistrib (Y n) (fun ω ↦ (history A Y n ω, A n ω)) (env.feedback n) P

lemma IsAlgEnvSeqUntil.mono (h : IsAlgEnvSeqUntil A Y alg env P N) {N' : ℕ} (hN : N' ≤ N) :
    IsAlgEnvSeqUntil A Y alg env P N' where
  measurable_action := h.measurable_action
  measurable_feedback := h.measurable_feedback
  hasCondDistrib_action n hn := h.hasCondDistrib_action n (hn.trans_le hN)
  hasCondDistrib_feedback n hn := h.hasCondDistrib_feedback n (hn.trans_le hN)

lemma IsAlgEnvSeq.isAlgEnvSeqUntil (h : IsAlgEnvSeq A Y alg env P) (N : ℕ) :
    IsAlgEnvSeqUntil A Y alg env P N where
  measurable_action := h.measurable_action
  measurable_feedback := h.measurable_feedback
  hasCondDistrib_action n _ := h.hasCondDistrib_action n
  hasCondDistrib_feedback n _ := h.hasCondDistrib_feedback n

lemma isAlgEnvSeq_iff_forall_isAlgEnvSeqUntil :
    IsAlgEnvSeq A Y alg env P ↔ ∀ N, IsAlgEnvSeqUntil A Y alg env P N where
  mp h N := h.isAlgEnvSeqUntil N
  mpr h := {
    measurable_action := (h 0).measurable_action
    measurable_feedback := (h 0).measurable_feedback
    hasCondDistrib_action n := (h (n + 1)).hasCondDistrib_action n n.lt_succ_self
    hasCondDistrib_feedback n := (h (n + 1)).hasCondDistrib_feedback n n.lt_succ_self }

@[fun_prop]
lemma IsAlgEnvSeq.measurable_step (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    Measurable (step A Y n) := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  fun_prop

@[fun_prop]
lemma IsAlgEnvSeq.measurable_history (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    Measurable (history A Y n) := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  fun_prop

@[fun_prop]
lemma IsAlgEnvSeq.measurable_trajectory (h : IsAlgEnvSeq A Y alg env P) :
    Measurable (trajectory A Y) :=
  Learning.measurable_trajectory h.measurable_action h.measurable_feedback

@[fun_prop]
lemma IsAlgEnvSeqUntil.measurable_step (h : IsAlgEnvSeqUntil A Y alg env P N) (n : ℕ) :
    Measurable (step A Y n) := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  fun_prop

@[fun_prop]
lemma IsAlgEnvSeqUntil.measurable_history (h : IsAlgEnvSeqUntil A Y alg env P N) (n : ℕ) :
    Measurable (history A Y n) := by
  have hA := h.measurable_action
  have hY := h.measurable_feedback
  fun_prop

lemma IsAlgEnvSeq.hasCondDistrib_step (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    HasCondDistrib (step A Y n) (history A Y n) (stepKernel alg env n) P :=
  HasCondDistrib.prod (h.hasCondDistrib_action n) (h.hasCondDistrib_feedback n)

lemma IsAlgEnvSeqUntil.hasCondDistrib_step (h : IsAlgEnvSeqUntil A Y alg env P N)
    (n : ℕ) (hn : n < N) :
    HasCondDistrib (step A Y n) (history A Y n) (stepKernel alg env n) P :=
  HasCondDistrib.prod (h.hasCondDistrib_action n hn) (h.hasCondDistrib_feedback n hn)

section Zero

/-! ### Laws at time `0`

At time `0` the history is the unique element of `Fin 0 → 𝓐 × 𝓨`: conditioning on it is the same
as not conditioning. Note that those results need `P` to be a probability measure. -/

variable [IsProbabilityMeasure P]

omit [IsFiniteMeasure P] in
/-- The history before time `0` is a constant. -/
lemma hasLaw_history_zero (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) :
    HasLaw (history A Y 0) (Measure.dirac default) P where
  aemeasurable := by rw [history_zero]; exact aemeasurable_const
  map_eq := by rw [history_zero, Measure.map_const, measure_univ, one_smul]

lemma IsAlgEnvSeqUntil.hasLaw_action_zero (h : IsAlgEnvSeqUntil A Y alg env P N) (hN : 0 < N) :
    HasLaw (A 0) alg.p0 P := by
  have h0 := h.hasCondDistrib_action 0 hN
  rw [history_zero] at h0
  exact h0.hasLaw_of_const'

lemma IsAlgEnvSeq.hasLaw_action_zero (h : IsAlgEnvSeq A Y alg env P) :
    HasLaw (A 0) alg.p0 P :=
  (h.isAlgEnvSeqUntil 1).hasLaw_action_zero zero_lt_one

omit [IsProbabilityMeasure P] in
lemma IsAlgEnvSeqUntil.hasCondDistrib_feedback_zero (h : IsAlgEnvSeqUntil A Y alg env P N)
    (hN : 0 < N) :
    HasCondDistrib (Y 0) (A 0) env.ν0 P :=
  hasCondDistrib_prodMk_left_unique_iff.mp (h.hasCondDistrib_feedback 0 hN)

omit [IsProbabilityMeasure P] in
lemma IsAlgEnvSeq.hasCondDistrib_feedback_zero (h : IsAlgEnvSeq A Y alg env P) :
    HasCondDistrib (Y 0) (A 0) env.ν0 P :=
  (h.isAlgEnvSeqUntil 1).hasCondDistrib_feedback_zero zero_lt_one

lemma IsAlgEnvSeqUntil.hasLaw_step_zero (h : IsAlgEnvSeqUntil A Y alg env P N) (hN : 0 < N) :
    HasLaw (step A Y 0) (alg.p0 ⊗ₘ env.ν0) P := by
  have h0 := h.hasCondDistrib_step 0 hN
  rw [history_zero] at h0
  rw [← stepKernel_zero alg env default]
  exact h0.hasLaw_of_const'

lemma IsAlgEnvSeq.hasLaw_step_zero (h : IsAlgEnvSeq A Y alg env P) :
    HasLaw (step A Y 0) (alg.p0 ⊗ₘ env.ν0) P :=
  (h.isAlgEnvSeqUntil 1).hasLaw_step_zero zero_lt_one

end Zero

lemma IsAlgEnvSeq.hasLaw_action_comp (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    HasLaw (A n) (alg.policy n ∘ₘ (P.map (history A Y n))) P :=
  HasCondDistrib.hasLaw_comp (h.hasCondDistrib_action n)

lemma IsAlgEnvSeq.hasLaw_feedback_comp (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    HasLaw (Y n) ((env.feedback n) ∘ₘ (P.map fun ω ↦ (history A Y n ω, A n ω))) P :=
  HasCondDistrib.hasLaw_comp (h.hasCondDistrib_feedback n)

lemma IsAlgEnvSeq.hasLaw_step_comp (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    HasLaw (step A Y n) (stepKernel alg env n ∘ₘ (P.map (history A Y n))) P :=
  HasCondDistrib.hasLaw_comp (h.hasCondDistrib_step n)

section Filtration

namespace IsAlgEnvSeq

/-- Filtration generated by the history up to time `n` (included): `h.filtration n` is the
σ-algebra generated by `history A Y (n + 1)`, that is by the action-feedback pairs at times
`0, ..., n`. -/
def filtration (h : IsAlgEnvSeq A Y alg env P) :
    Filtration ℕ mΩ where
  seq n := MeasurableSpace.comap (history A Y (n + 1)) inferInstance
  mono' i j hij := by
    simp only
    rw [← measurable_iff_comap_le, history_eq_comp_history (Nat.succ_le_succ hij)]
    exact measurable_comp_comap _ (by fun_prop)
  le' i := by
    rw [← measurable_iff_comap_le]
    exact Learning.measurable_history h.measurable_action h.measurable_feedback _

lemma filtration_eq_comap (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    h.filtration n = MeasurableSpace.comap (history A Y (n + 1)) inferInstance := rfl

lemma measurable_history_succ_filtration (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    Measurable[h.filtration n] (history A Y (n + 1)) :=
  measurable_iff_comap_le.mpr le_rfl

lemma adapted_history (h : IsAlgEnvSeq A Y alg env P) :
    Adapted h.filtration (history A Y) := by
  intro n
  rw [history_eq_comp_history n.le_succ]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_step (h : IsAlgEnvSeq A Y alg env P) :
    Adapted h.filtration (step A Y) := by
  intro n
  rw [← eval_comp_history]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_action (h : IsAlgEnvSeq A Y alg env P) :
    Adapted h.filtration A := by
  intro n
  rw [← fst_eval_comp_history (A := A) (Y := Y) n]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_feedback (h : IsAlgEnvSeq A Y alg env P) :
    Adapted h.filtration Y := by
  intro n
  rw [← snd_eval_comp_history (A := A) (Y := Y) n]
  exact measurable_comp_comap _ (by fun_prop)

/-- Filtration generated by the history before time `n` together with the action at time `n`. -/
def filtrationAction (h : IsAlgEnvSeq A Y alg env P) :
    Filtration ℕ mΩ where
  seq n := MeasurableSpace.comap (fun ω ↦ (history A Y n ω, A n ω)) inferInstance
  mono' n m hnm := by
    simp only
    rw [← measurable_iff_comap_le]
    rcases eq_or_lt_of_le hnm with rfl | hlt
    · exact measurable_iff_comap_le.mpr le_rfl
    have : (fun ω ↦ (history A Y n ω, A n ω)) =
        (fun p : (Fin m → 𝓐 × 𝓨) × 𝓐 ↦
          (fun i : Fin n ↦ p.1 (Fin.castLE hnm i), (p.1 ⟨n, hlt⟩).1)) ∘
        (fun ω ↦ (history A Y m ω, A m ω)) := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)
  le' n := by
    rw [← measurable_iff_comap_le]
    exact (Learning.measurable_history h.measurable_action h.measurable_feedback n).prodMk
      (h.measurable_action n)

lemma filtrationAction_eq_comap (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    h.filtrationAction n =
      MeasurableSpace.comap (fun ω ↦ (history A Y n ω, A n ω)) inferInstance := rfl

lemma filtrationAction_zero_eq_comap (h : IsAlgEnvSeq A Y alg env P) :
    h.filtrationAction 0 = MeasurableSpace.comap (A 0) inferInstance := by
  rw [filtrationAction_eq_comap, history_zero]
  refine le_antisymm ?_ ?_
  · rw [← measurable_iff_comap_le]
    exact measurable_const.prodMk (measurable_iff_comap_le.mpr le_rfl)
  · rw [← measurable_iff_comap_le]
    exact measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl)

@[fun_prop]
lemma measurable_history_filtrationAction (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    Measurable[h.filtrationAction n] (history A Y n) :=
  measurable_fst.comp (measurable_iff_comap_le.mpr le_rfl)

lemma filtration_le_filtrationAction_succ (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    h.filtration n ≤ h.filtrationAction (n + 1) :=
  measurable_iff_comap_le.mp (h.measurable_history_filtrationAction (n + 1))

lemma filtrationAction_le_filtration (h : IsAlgEnvSeq A Y alg env P) (n : ℕ) :
    h.filtrationAction n ≤ h.filtration n := by
  rw [filtrationAction_eq_comap, ← measurable_iff_comap_le]
  exact (h.adapted_history n).prodMk (h.adapted_action n)

lemma adapted_action_filtrationAction (h : IsAlgEnvSeq A Y alg env P) :
    Adapted h.filtrationAction A := fun _ ↦
  measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl)

lemma measurable_feedback_filtrationAction_of_lt (h : IsAlgEnvSeq A Y alg env P)
    {m n : ℕ} (hmn : m < n) :
    Measurable[h.filtrationAction n] (Y m) := by
  obtain ⟨j, rfl⟩ : ∃ j, n = j + 1 := ⟨n - 1, by lia⟩
  exact (h.adapted_feedback.measurable_le (by lia)).mono
    (filtration_le_filtrationAction_succ h j) le_rfl

end IsAlgEnvSeq

end Filtration

end IsAlgEnvSeq

end Learning
