/-
Copyright (c) 2026 Paulo Rauber. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paulo Rauber, Rémy Degenne
-/
module

public import LeanMachineLearning.SequentialLearning.Announce
public import LeanMachineLearning.SequentialLearning.StationaryEnv

/-!
# Bayesian stationary environments

A Bayesian stationary environment is an environment that draws a parameter `e : 𝓔` from a prior
`Q` before the first round and then behaves like the stationary environment
`stationaryEnv (κ.sectR e)`. Following the "announced variables" mechanism of
`LeanMachineLearning/SequentialLearning/Announce.lean`, the parameter is not hidden: it is part of
the environment's move, and the algorithm is the one that ignores it. Concretely,
`bayesEnv Q κ : Environment (𝓔 × Unit) 𝓐 𝓨` announces `e` in every observation and runs against
`alg.comapObs Prod.snd`, for an `alg : Algorithm Unit 𝓐 𝓨`.

The predicate `IsBayesAlgEnvSeq` is not a new notion of run: it is `IsAlgEnvSeq` for that pair,
for the observation process that announces the parameter `E` at every round.

## Main definitions

* `bayesEnv Q κ`: the environment that draws a parameter from `Q` before the first round, announces
  it in the first component of every observation, and returns feedback `κ (e, a)` when the
  parameter is `e` and the action is `a`.
* `IsBayesAlgEnvSeq Q κ alg E A Y P`: states that the parameter `E : Ω → 𝓔` has law `Q` and that
  the sequences of actions `A : ℕ → Ω → 𝓐` and feedbacks `Y : ℕ → Ω → 𝓨` are generated by the
  algorithm `alg : Algorithm Unit 𝓐 𝓨` interacting with `bayesEnv Q κ`, which it sees through
  `Algorithm.comapObs Prod.snd`. Equivalently, `A` and `Y` are generated by `alg` interacting with
  the stationary environment `stationaryEnv (κ.sectR (E ω))`.
* `bayesTrajMeasure Q κ alg`: for any choice of probability measure `Q : Measure 𝓔`, Markov kernel
  `κ : Kernel (𝓔 × 𝓐) 𝓨`, and algorithm `alg : Algorithm Unit 𝓐 𝓨`, provides a probability measure
  `P : Measure (ℕ → Round (𝓔 × Unit) 𝓐 𝓨)` on a space that carries `E`, `A`, and `Y` such that
  `IsBayesAlgEnvSeq Q κ alg E A Y P`.
* `bayesTrajMeasurePosterior Q κ alg n`: a `Kernel (Hist Unit 𝓐 𝓨 n) 𝓔` that represents the
  posterior over `E` given the history before time `n` (the `n` first rounds) under
  the prior `Q` and the algorithm `alg`, assuming that the kernel `κ` specifies how `E` gives rise
  to the underlying (stationary) environment.
  See also `LeanMachineLearning/SequentialLearning/AlgorithmDensityBayes.lean`.

## Main results

* `IsAlgEnvSeq.isBayesAlgEnvSeq`: a run of `alg.comapObs Prod.snd` against `bayesEnv Q κ` is a
  Bayesian algorithm-environment sequence for the announced parameter.
* `ae_IsAlgEnvSeq h`: if `h : IsBayesAlgEnvSeq Q κ alg E A Y P`, for `Q`-almost every `e : 𝓔`,
  `IsAlgEnvSeq O' A' Y' alg (stationaryEnv (κ.sectR e)) (condDistrib (trajectory _ A Y) E P e)` for
  some sequence of actions `A' : ℕ → (ℕ → Round Unit 𝓐 𝓨) → 𝓐` and sequence of feedbacks
  `Y' : ℕ → (ℕ → Round Unit 𝓐 𝓨) → 𝓨`. Intuitively, if the observable trajectory is generated by an
  underlying parameter `e : 𝓔`, the measure that carries the `IsBayesAlgEnvSeq` structure reveals a
  measure that carries an `IsAlgEnvSeq` structure under the environment `stationaryEnv (κ.sectR e)`
  and the same algorithm. This allows transferring results from the `IsAlgEnvSeq` structure to the
  `IsBayesAlgEnvSeq` structure.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Finset
open scoped ENNReal NNReal

namespace Learning

variable {𝓔 𝓐 𝓨 Ω : Type*}
variable [MeasurableSpace 𝓔] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω]

section BayesEnv

/-- The environment that draws a parameter `e : 𝓔` from `Q` before the first round, announces it in
the first component of every observation, and returns a feedback drawn from `κ (e, a)` when the
action is `a`. The algorithm is meant to ignore the announced parameter, that is, to run through
`Algorithm.comapObs Prod.snd`. -/
noncomputable
def bayesEnv (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ] :
    Environment (𝓔 × Unit) 𝓐 𝓨 where
  obs
    | 0 => Kernel.const _ (Q.prod (Measure.dirac ()))
    | _ + 1 => Kernel.deterministic (fun h ↦ (h 0).obs) (by fun_prop)
  feedback _ := κ.comap (fun p ↦ (p.1.2.1, p.2)) (by fun_prop)
  isMarkovKernel_obs n := by cases n <;> infer_instance

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]

@[simp]
lemma obs_bayesEnv_zero :
    (bayesEnv Q κ).obs 0 = Kernel.const _ (Q.prod (Measure.dirac ())) := rfl

@[simp]
lemma obs_bayesEnv_succ (n : ℕ) :
    (bayesEnv Q κ).obs (n + 1)
      = Kernel.deterministic (fun h : Hist (𝓔 × Unit) 𝓐 𝓨 (n + 1) ↦ (h 0).obs) (by fun_prop) := rfl

@[simp]
lemma feedback_bayesEnv (n : ℕ) :
    (bayesEnv Q κ).feedback n = κ.comap (fun p ↦ (p.1.2.1, p.2)) (by fun_prop) := rfl

@[simp]
lemma obs0_bayesEnv : (bayesEnv Q κ).obs0 = Q.prod (Measure.dirac ()) := rfl

@[simp]
lemma ν0_bayesEnv : (bayesEnv Q κ).ν0 = κ.comap (fun p ↦ (p.1.1, p.2)) (by fun_prop) := rfl

end BayesEnv

/-- Insert an announced parameter `e` into every round of an observable history. -/
def announceHist (e : 𝓔) {n : ℕ} (h : Hist Unit 𝓐 𝓨 n) : Hist (𝓔 × Unit) 𝓐 𝓨 n :=
  fun i ↦ ((e, ()), (h i).action, (h i).feedback)

@[fun_prop]
lemma measurable_announceHist (n : ℕ) :
    Measurable (fun p : 𝓔 × Hist Unit 𝓐 𝓨 n ↦ announceHist p.1 p.2) := by
  unfold announceHist
  fun_prop

/-- `IsBayesAlgEnvSeq Q κ alg E A Y P` states that there is a measure `P : Measure Ω` such
that the parameter `E : Ω → 𝓔` has law `Q` and that the sequences of actions `A : ℕ → Ω → 𝓐`
and feedbacks `Y : ℕ → Ω → 𝓨` are generated by the algorithm `alg : Algorithm Unit 𝓐 𝓨`
interacting with an underlying environment that depends on `E` and `κ`
(`stationaryEnv (κ.sectR (E ω))`).

This is `IsAlgEnvSeq` for the announcing environment `bayesEnv Q κ` and the algorithm
`alg.comapObs Prod.snd` that ignores the announced parameter: the observation at every round is
`(E ω, ())`. -/
def IsBayesAlgEnvSeq (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] (alg : Algorithm Unit 𝓐 𝓨)
    (E : Ω → 𝓔) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (P : Measure Ω) [IsProbabilityMeasure P] : Prop :=
  IsAlgEnvSeq (fun _ ω ↦ (E ω, ())) A Y (alg.comapObs Prod.snd) (bayesEnv Q κ) P

namespace IsBayesAlgEnvSeq

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]
variable {alg : Algorithm Unit 𝓐 𝓨}
variable {E : Ω → 𝓔} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
variable {P : Measure Ω} [IsProbabilityMeasure P]

/-- Constructor for `IsBayesAlgEnvSeq` from the law of the parameter and the conditional
distributions of the actions and of the feedbacks given the parameter and the observable history.
Together with `IsBayesAlgEnvSeq.hasLaw_env`, `IsBayesAlgEnvSeq.hasCondDistrib_action` and
`IsBayesAlgEnvSeq.hasCondDistrib_feedback`, this shows that being an `IsAlgEnvSeq` for the
announcing environment is equivalent to those conditions. -/
lemma mk (hasLaw_env : HasLaw E Q P)
    (hasCondDistrib_action : ∀ n,
      HasCondDistrib (A n) (fun ω ↦ (E ω, (history (noObs Ω) A Y n ω, noObs Ω n ω)))
        ((alg.policy n).prodMkLeft _) P)
    (hasCondDistrib_feedback : ∀ n,
      HasCondDistrib (Y n) (fun ω ↦ ((history (noObs Ω) A Y n ω, noObs Ω n ω), (E ω, A n ω)))
        (κ.prodMkLeft _) P)
    (measurable_param : Measurable E := by fun_prop)
    (measurable_action : ∀ n, Measurable (A n) := by fun_prop)
    (measurable_feedback : ∀ n, Measurable (Y n) := by fun_prop) :
    IsBayesAlgEnvSeq Q κ alg E A Y P := by
  have hO : ∀ _ : ℕ, Measurable (fun ω ↦ ((E ω, ()) : 𝓔 × Unit)) :=
    fun _ ↦ measurable_param.prodMk measurable_const
  refine IsAlgEnvSeq.mk hO measurable_action measurable_feedback ?_ ?_ ?_
  · intro n
    cases n with
    | zero =>
      rw [history_zero, obs_bayesEnv_zero]
      refine HasLaw.hasCondDistrib_const ⟨(hO 0).aemeasurable, ?_⟩
      rw [Kernel.const_apply, Measure.prod_dirac, ← hasLaw_env.map_eq,
        AEMeasurable.map_map_of_aemeasurable (by fun_prop) hasLaw_env.aemeasurable]
      rfl
    | succ n =>
      rw [obs_bayesEnv_succ]
      exact hasCondDistrib_deterministic _
        (measurable_history hO measurable_action measurable_feedback (n + 1)).aemeasurable
        (ae_of_all _ fun _ ↦ rfl)
  · intro n
    exact HasCondDistrib.comp_right
      (f := fun q : 𝓔 × (Hist Unit 𝓐 𝓨 n × Unit) ↦ (announceHist q.1 q.2.1, (q.1, q.2.2)))
      (hf := by fun_prop)
      (Z := fun ω ↦ (E ω, (history (noObs Ω) A Y n ω, noObs Ω n ω)))
      (hasCondDistrib_action n)
  · intro n
    exact HasCondDistrib.comp_right
      (f := fun q : (Hist Unit 𝓐 𝓨 n × Unit) × (𝓔 × 𝓐) ↦
        ((announceHist q.2.1 q.1.1, (q.2.1, q.1.2)), q.2.2))
      (hf := by fun_prop)
      (Z := fun ω ↦ ((history (noObs Ω) A Y n ω, noObs Ω n ω), (E ω, A n ω)))
      (hasCondDistrib_feedback n)

/-- A Bayesian algorithm-environment sequence is an algorithm-environment sequence for the
announcing environment `bayesEnv Q κ`. -/
lemma isAlgEnvSeq (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    IsAlgEnvSeq (fun _ ω ↦ (E ω, ())) A Y (alg.comapObs Prod.snd) (bayesEnv Q κ) P := h

lemma measurable_param (h : IsBayesAlgEnvSeq Q κ alg E A Y P) : Measurable E :=
  (h.isAlgEnvSeq.measurable_obs 0).fst

lemma measurable_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) : Measurable (A n) :=
  h.isAlgEnvSeq.measurable_action n

lemma measurable_feedback (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) : Measurable (Y n) :=
  h.isAlgEnvSeq.measurable_feedback n

/-- The parameter has law `Q`. -/
lemma hasLaw_env (h : IsBayesAlgEnvSeq Q κ alg E A Y P) : HasLaw E Q P := by
  have h0 := h.isAlgEnvSeq.hasCondDistrib_obs 0
  rw [history_zero] at h0
  have h1 : HasLaw (fun ω ↦ (E ω, ())) (Q.prod (Measure.dirac ())) P := h0.hasLaw_of_const'
  refine ⟨h.measurable_param.aemeasurable, ?_⟩
  have h2 : E = Prod.fst ∘ (fun ω ↦ (E ω, ())) := rfl
  rw [h2, ← Measure.map_map measurable_fst
    (h.measurable_param.prodMk (measurable_const : Measurable fun _ : Ω ↦ ())), h1.map_eq]
  exact Measure.fst_prod

/-- The action at time `n` has the correct conditional distribution given the parameter and the
history: it depends only on the history. -/
lemma hasCondDistrib_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (A n) (fun ω ↦ (E ω, (history (noObs Ω) A Y n ω, noObs Ω n ω)))
      ((alg.policy n).prodMkLeft _) P :=
  HasCondDistrib.comp_right
    (f := fun p : Hist (𝓔 × Unit) 𝓐 𝓨 n × (𝓔 × Unit) ↦ (p.2.1, (Hist.mapObs Prod.snd p.1, p.2.2)))
    (hf := by fun_prop)
    (Z := fun ω ↦ (history (fun _ ω ↦ (E ω, ())) A Y n ω, (E ω, ())))
    (h.isAlgEnvSeq.hasCondDistrib_action n)

/-- The feedback at time `n` has the correct conditional distribution given the history, the
parameter and the action at time `n`: it depends only on the parameter and the action. -/
lemma hasCondDistrib_feedback (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (Y n) (fun ω ↦ ((history (noObs Ω) A Y n ω, noObs Ω n ω), (E ω, A n ω)))
      (κ.prodMkLeft _) P :=
  HasCondDistrib.comp_right
    (f := fun p : (Hist (𝓔 × Unit) 𝓐 𝓨 n × (𝓔 × Unit)) × 𝓐 ↦
      ((Hist.mapObs Prod.snd p.1.1, p.1.2.2), (p.1.2.1, p.2)))
    (hf := by fun_prop)
    (Z := fun ω ↦ ((history (fun _ ω ↦ (E ω, ())) A Y n ω, (E ω, ())), A n ω))
    (h.isAlgEnvSeq.hasCondDistrib_feedback n)

lemma hasCondDistrib_action' (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (A n) (fun ω ↦ (history (noObs Ω) A Y n ω, noObs Ω n ω)) (alg.policy n) P :=
  (h.hasCondDistrib_action n).comp_right

lemma hasCondDistrib_feedback' (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (Y n) (fun ω ↦ (E ω, A n ω)) κ P :=
  (h.hasCondDistrib_feedback n).comp_right

lemma hasLaw_action_zero (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    HasLaw (A 0) (alg.p0 ()) P := by
  have h0 : HasCondDistrib (A 0)
      (fun _ : Ω ↦ ((default : Hist Unit 𝓐 𝓨 0), ())) (alg.policy 0) P := by
    have h1 := h.hasCondDistrib_action' 0
    rwa [history_zero] at h1
  exact h0.hasLaw_of_const'

/-- The first action is independent of the parameter `E`, and has law `alg.p0 ()`. -/
lemma hasCondDistrib_action_zero (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    HasCondDistrib (A 0) E (Kernel.const _ (alg.p0 ())) P :=
  hasCondDistrib_prodMk_right_unique_iff.mp (h.hasCondDistrib_action 0)

variable [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨]

omit [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨] in
/-- The posterior over the parameter given the empty history is the prior. -/
lemma condDistrib_param_history_zero [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    condDistrib E (history (noObs Ω) A Y 0) P = Kernel.const _ Q := by
  ext x : 1
  rw [Unique.eq_default x, history_zero]
  have hc : HasCondDistrib E (fun _ : Ω ↦ (default : Hist Unit 𝓐 𝓨 0)) (Kernel.const _ Q) P :=
    h.hasLaw_env.hasCondDistrib_const
  have h_ae := hc.condDistrib_eq
  rw [Measure.map_const, measure_univ, one_smul, Filter.EventuallyEq,
    ae_dirac_iff Subsingleton.measurableSet] at h_ae
  exact h_ae

lemma hasCondDistrib_IT_obs (_h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.obs n) (IT.hist n) (unitObs 𝓐 𝓨 n)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) :=
  ae_of_all _ fun _ ↦ hasCondDistrib_unit (IT.measurable_hist n).aemeasurable _ _

lemma hasCondDistrib_IT_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.action n) (fun τ ↦ (IT.hist n τ, IT.obs n τ)) (alg.policy n)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq]
  filter_upwards [(h.hasCondDistrib_action n).hasCondDistrib_sectR
    ((IT.measurable_hist n).prodMk (IT.measurable_obs n)) (IT.measurable_action n)
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable] with _ he
  rwa [Kernel.sectR_prodMkLeft] at he

lemma hasCondDistrib_IT_feedback (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.feedback n)
      (fun τ ↦ ((IT.hist n τ, IT.obs n τ), IT.action n τ))
      ((κ.sectR e).prodMkLeft _) (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq]
  have hc : HasCondDistrib (Y n)
      (fun ω ↦ (E ω, ((history (noObs Ω) A Y n ω, noObs Ω n ω), A n ω)))
      (κ.comap (fun p : 𝓔 × ((Hist Unit 𝓐 𝓨 n × Unit) × 𝓐) ↦ (p.1, p.2.2)) (by fun_prop)) P :=
    (h.hasCondDistrib_feedback n).measurableEquiv_comp_right (MeasurableEquiv.prodAssoc.symm.trans
      ((MeasurableEquiv.prodCongr .prodComm (.refl _)).trans .prodAssoc))
  exact hc.hasCondDistrib_sectR
    (((IT.measurable_hist n).prodMk (IT.measurable_obs n)).prodMk (IT.measurable_action n))
    (IT.measurable_feedback n)
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable

lemma hasLaw_IT_hist (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasLaw (IT.hist n) (condDistrib (history (noObs Ω) A Y n) E P e)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq, show history (noObs Ω) A Y n
    = IT.hist (𝓞 := Unit) (𝓐 := 𝓐) (𝓨 := 𝓨) n ∘ trajectory (noObs Ω) A Y from rfl]
  filter_upwards [condDistrib_comp E
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable
    (IT.measurable_hist (𝓞 := Unit) (𝓐 := 𝓐) (𝓨 := 𝓨) n)] with _ he
  exact ⟨(IT.measurable_hist n).aemeasurable, by
    rw [← Kernel.map_apply _ (IT.measurable_hist n), he]⟩

lemma ae_IsAlgEnvSeq (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    ∀ᵐ e ∂Q, IsAlgEnvSeq IT.obs IT.action IT.feedback alg (stationaryEnv (κ.sectR e))
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  filter_upwards [ae_all_iff.2 (hasCondDistrib_IT_obs h),
    ae_all_iff.2 (hasCondDistrib_IT_action h),
    ae_all_iff.2 (hasCondDistrib_IT_feedback h)] with _ hO hA hR
  exact ⟨IT.measurable_obs, IT.measurable_action, IT.measurable_feedback, hO, hA, hR⟩

end IsBayesAlgEnvSeq

section IsAlgEnvSeq

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]
variable {alg : Algorithm Unit 𝓐 𝓨} {O : ℕ → Ω → 𝓔 × Unit} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
variable {P : Measure Ω} [IsProbabilityMeasure P]

/-- Under `bayesEnv Q κ`, the announced parameter is almost surely the same at every round. -/
lemma IsAlgEnvSeq.ae_obs_eq_obs_zero [StandardBorelSpace 𝓔]
    (h : IsAlgEnvSeq O A Y (alg.comapObs Prod.snd) (bayesEnv Q κ) P) (n : ℕ) :
    (fun ω ↦ ((O 0 ω).1, ())) =ᵐ[P] O n := by
  cases n with
  | zero => exact ae_of_all _ fun _ ↦ rfl
  | succ n =>
    have h1 := h.hasCondDistrib_obs (n + 1)
    rw [obs_bayesEnv_succ] at h1
    have h2 := ae_eq_of_hasCondDistrib_deterministic (by fun_prop)
      (h.measurable_history (n + 1)).aemeasurable (h.measurable_obs (n + 1)).aemeasurable h1
    filter_upwards [h2] with ω hω
    rw [hω]
    simp [history_apply]

/-- A run of `alg.comapObs Prod.snd` against the announcing environment `bayesEnv Q κ` is a
Bayesian algorithm-environment sequence for the announced parameter. -/
lemma IsAlgEnvSeq.isBayesAlgEnvSeq [StandardBorelSpace 𝓔]
    (h : IsAlgEnvSeq O A Y (alg.comapObs Prod.snd) (bayesEnv Q κ) P) :
    IsBayesAlgEnvSeq Q κ alg (fun ω ↦ (O 0 ω).1) A Y P :=
  h.congr (fun _ ↦ (h.measurable_obs 0).fst.prodMk measurable_const)
    h.measurable_action h.measurable_feedback h.ae_obs_eq_obs_zero
    (fun _ ↦ .rfl) (fun _ ↦ .rfl)

end IsAlgEnvSeq

namespace IT

/-- A measure `P` on a measurable space that carries random variables `E`, `A`, and `Y` such that
`IsBayesAlgEnvSeq Q κ alg E A Y P`. -/
noncomputable
def bayesTrajMeasure (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] (alg : Algorithm Unit 𝓐 𝓨) : Measure (ℕ → Round (𝓔 × Unit) 𝓐 𝓨) :=
  trajMeasure (alg.comapObs Prod.snd) (bayesEnv Q κ)
deriving IsProbabilityMeasure

/-- The parameter announced by `bayesEnv Q κ`, read on the trajectory space. -/
def param (τ : ℕ → Round (𝓔 × Unit) 𝓐 𝓨) : 𝓔 := (IT.obs 0 τ).1

@[fun_prop]
lemma measurable_param : Measurable (param (𝓔 := 𝓔) (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold param; fun_prop

lemma isBayesAlgEnvSeq_bayesTrajMeasure [StandardBorelSpace 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) :
    IsBayesAlgEnvSeq Q κ alg param action feedback (bayesTrajMeasure Q κ alg) :=
  (isAlgEnvSeq_trajMeasure _ _).isBayesAlgEnvSeq

/-- A kernel that represents the posterior over `E` given the history before time `n`. -/
noncomputable
def bayesTrajMeasurePosterior [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) (n : ℕ) : Kernel (Hist Unit 𝓐 𝓨 n) 𝓔 :=
  condDistrib param (history (noObs _) action feedback n) (bayesTrajMeasure Q κ alg)
deriving IsMarkovKernel

/-- The posterior given the empty history is the prior. -/
lemma bayesTrajMeasurePosterior_zero [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) :
    bayesTrajMeasurePosterior Q κ alg 0 = Kernel.const _ Q :=
  (isBayesAlgEnvSeq_bayesTrajMeasure Q κ alg).condDistrib_param_history_zero

end IT

end Learning
