/-
Copyright (c) 2026 Paulo Rauber. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Paulo Rauber, Rémy Degenne
-/
module

public import LeanMachineLearning.SequentialLearning.IonescuTulceaSpace
public import LeanMachineLearning.SequentialLearning.StationaryEnv

/-!
# Bayesian stationary environments

This file defines the structure `IsBayesAlgEnvSeq` and provides its basic properties.
The underlying environments are stationary environments, which have no observations: the
observation type is `Unit` and the observation process is `noObs`.

## Main definitions

* `IsBayesAlgEnvSeq Q κ alg E A Y P`: states that there is a measure `P : Measure Ω` such
  that the parameter `E : Ω → 𝓔` has law `Q` and that the sequences of actions `A : ℕ → Ω → 𝓐`
  and feedbacks `Y : ℕ → Ω → 𝓨` are generated by the algorithm `alg : Algorithm Unit 𝓐 𝓨`
  interacting with an underlying environment that depends on `E` and `κ`
  (`stationaryEnv (κ.sectR (E ω))`).
* `bayesTrajMeasure Q κ alg`: for any choice of probability measure `Q : Measure 𝓔`, Markov kernel
  `κ : Kernel (𝓔 × 𝓐) 𝓨`, and algorithm `alg : Algorithm Unit 𝓐 𝓨`, provides a probability measure
  `P : Measure (ℕ → Round Unit 𝓐 (𝓔 × 𝓨))` on a space that carries `E`, `A`, and `Y` such that
  `IsBayesAlgEnvSeq Q κ alg E A Y P`.
* `bayesTrajMeasurePosterior Q κ alg n`: a `Kernel (Hist Unit 𝓐 𝓨 n) 𝓔` that represents the
  posterior over `E` given the history before time `n` (the `n` first rounds) under
  the prior `Q` and the algorithm `alg`, assuming that the kernel `κ` specifies how `E` gives rise
  to the underlying (stationary) environment.
  See also `LeanMachineLearning/SequentialLearning/AlgorithmDensityBayes.lean`.

## Main results

* `ae_IsAlgEnvSeq h`: if `h : IsBayesAlgEnvSeq Q κ alg E A Y P`, for `Q`-almost every `e : 𝓔`,
  `IsAlgEnvSeq O' A' Y' alg (stationaryEnv (κ.sectR e)) (condDistrib (trajectory _ A Y) E P e)` for
  some sequence of actions `A' : ℕ → (ℕ → Round Unit 𝓐 𝓨) → 𝓐` and sequence of feedbacks
  `Y' : ℕ → (ℕ → Round Unit 𝓐 𝓨) → 𝓨`. Intuitively, if the observable trajectory is generated by an
  underlying parameter `e : 𝓔`, the measure that carries the `IsBayesAlgEnvSeq` structure reveals a
  measure that carries an `IsAlgEnvSeq` structure under the environment `stationaryEnv (κ.sectR e)`
  and the same algorithm. This allows transferring results from the `IsAlgEnvSeq` structure to the
  `IsBayesAlgEnvSeq` structure.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Finset
open scoped ENNReal NNReal

namespace Learning

variable {𝓔 𝓐 𝓨 Ω : Type*}
variable [MeasurableSpace 𝓔] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] [MeasurableSpace Ω]

/-- `IsBayesAlgEnvSeq Q κ alg E A Y P` states that there is a measure `P : Measure Ω` such
  that the parameter `E : Ω → 𝓔` has law `Q` and that the sequences of actions `A : ℕ → Ω → 𝓐`
  and feedbacks `Y : ℕ → Ω → 𝓨` are generated by the algorithm `alg : Algorithm Unit 𝓐 𝓨`
  interacting with an underlying environment that depends on `E` and `κ`
  (`stationaryEnv (κ.sectR (E ω))`). -/
structure IsBayesAlgEnvSeq
    (Q : Measure 𝓔) (κ : Kernel (𝓔 × 𝓐) 𝓨) (alg : Algorithm Unit 𝓐 𝓨)
    (E : Ω → 𝓔) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  measurable_param : Measurable E := by fun_prop
  measurable_action n : Measurable (A n) := by fun_prop
  measurable_feedback n : Measurable (Y n) := by fun_prop
  hasLaw_env : HasLaw E Q P
  /-- The action at time `n` has the correct conditional distribution given the parameter and the
  history: it depends only on the history. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (E ω, (history (noObs Ω) A Y n ω, noObs Ω n ω)))
      ((alg.policy n).prodMkLeft _) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  parameter and the action at time `n`: it depends only on the parameter and the action. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history (noObs Ω) A Y n ω, noObs Ω n ω), E ω, A n ω))
      (κ.prodMkLeft _) P

namespace IsBayesAlgEnvSeq

variable {Q : Measure 𝓔} {κ : Kernel (𝓔 × 𝓐) 𝓨} {alg : Algorithm Unit 𝓐 𝓨}
variable {E : Ω → 𝓔} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
variable {P : Measure Ω} [IsFiniteMeasure P]

lemma hasCondDistrib_action' (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (A n) (fun ω ↦ (history (noObs Ω) A Y n ω, noObs Ω n ω)) (alg.policy n) P :=
  (h.hasCondDistrib_action n).comp_right

lemma hasCondDistrib_feedback' [IsFiniteKernel κ] (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    HasCondDistrib (Y n) (fun ω ↦ (E ω, A n ω)) κ P :=
  (h.hasCondDistrib_feedback n).comp_right

lemma hasLaw_action_zero [IsProbabilityMeasure P] (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    HasLaw (A 0) (alg.p0 ()) P := by
  have h0 : HasCondDistrib (A 0)
      (fun _ : Ω ↦ ((default : Hist Unit 𝓐 𝓨 0), ())) (alg.policy 0) P := by
    have h1 := h.hasCondDistrib_action' 0
    rwa [history_zero] at h1
  exact h0.hasLaw_of_const'

/-- The first action is independent of the parameter `E`, and has law `alg.p0 ()`. -/
lemma hasCondDistrib_action_zero (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    HasCondDistrib (A 0) E (Kernel.const _ (alg.p0 ())) P :=
  hasCondDistrib_prodMk_right_unique_iff.mp (h.hasCondDistrib_action 0)

variable [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨]

omit [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨] in
/-- The posterior over the parameter given the empty history is the prior. -/
lemma condDistrib_param_history_zero [StandardBorelSpace 𝓔] [Nonempty 𝓔] [IsProbabilityMeasure P]
    [IsFiniteMeasure Q] (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    condDistrib E (history (noObs Ω) A Y 0) P = Kernel.const _ Q := by
  ext x : 1
  rw [Unique.eq_default x, history_zero]
  have hc : HasCondDistrib E (fun _ : Ω ↦ (default : Hist Unit 𝓐 𝓨 0)) (Kernel.const _ Q) P :=
    h.hasLaw_env.hasCondDistrib_const
  have h_ae := hc.condDistrib_eq
  rw [Measure.map_const, measure_univ, one_smul, Filter.EventuallyEq,
    ae_dirac_iff Subsingleton.measurableSet] at h_ae
  exact h_ae

lemma hasCondDistrib_IT_obs [IsProbabilityMeasure P] (_h : IsBayesAlgEnvSeq Q κ alg E A Y P)
    (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.obs n) (IT.hist n) (unitObs 𝓐 𝓨 n)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) :=
  ae_of_all _ fun _ ↦ hasCondDistrib_unit (IT.measurable_hist n).aemeasurable _ _

lemma hasCondDistrib_IT_action (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.action n) (fun τ ↦ (IT.hist n τ, IT.obs n τ)) (alg.policy n)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq]
  filter_upwards [(h.hasCondDistrib_action n).hasCondDistrib_sectR
    ((IT.measurable_hist n).prodMk (IT.measurable_obs n)) (IT.measurable_action n)
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable] with _ he
  rwa [Kernel.sectR_prodMkLeft] at he

lemma hasCondDistrib_IT_feedback [IsFiniteKernel κ] (h : IsBayesAlgEnvSeq Q κ alg E A Y P)
    (n : ℕ) :
    ∀ᵐ e ∂Q, HasCondDistrib (IT.feedback n)
      (fun τ ↦ ((IT.hist n τ, IT.obs n τ), IT.action n τ))
      ((κ.sectR e).prodMkLeft _) (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq]
  have hc : HasCondDistrib (Y n)
      (fun ω ↦ (E ω, ((history (noObs Ω) A Y n ω, noObs Ω n ω), A n ω)))
      (κ.comap (fun p : 𝓔 × ((Hist Unit 𝓐 𝓨 n × Unit) × 𝓐) ↦ (p.1, p.2.2)) (by fun_prop)) P :=
    (h.hasCondDistrib_feedback n).measurableEquiv_comp_right (MeasurableEquiv.prodAssoc.symm.trans
      ((MeasurableEquiv.prodCongr .prodComm (.refl _)).trans .prodAssoc))
  exact hc.hasCondDistrib_sectR
    (((IT.measurable_hist n).prodMk (IT.measurable_obs n)).prodMk (IT.measurable_action n))
    (IT.measurable_feedback n)
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable

lemma hasLaw_IT_hist (h : IsBayesAlgEnvSeq Q κ alg E A Y P) (n : ℕ) :
    ∀ᵐ e ∂Q, HasLaw (IT.hist n) (condDistrib (history (noObs Ω) A Y n) E P e)
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  rw [← h.hasLaw_env.map_eq, show history (noObs Ω) A Y n
    = IT.hist (𝓞 := Unit) (𝓐 := 𝓐) (𝓨 := 𝓨) n ∘ trajectory (noObs Ω) A Y from rfl]
  filter_upwards [condDistrib_comp E
    (measurable_trajectory (O := noObs Ω) (fun _ ↦ measurable_const) h.measurable_action
      h.measurable_feedback).aemeasurable
    (IT.measurable_hist (𝓞 := Unit) (𝓐 := 𝓐) (𝓨 := 𝓨) n)] with _ he
  exact ⟨(IT.measurable_hist n).aemeasurable, by
    rw [← Kernel.map_apply _ (IT.measurable_hist n), he]⟩

lemma ae_IsAlgEnvSeq [IsProbabilityMeasure P] [IsMarkovKernel κ]
    (h : IsBayesAlgEnvSeq Q κ alg E A Y P) :
    ∀ᵐ e ∂Q, IsAlgEnvSeq IT.obs IT.action IT.feedback alg (stationaryEnv (κ.sectR e))
      (condDistrib (trajectory (noObs Ω) A Y) E P e) := by
  filter_upwards [ae_all_iff.2 (hasCondDistrib_IT_obs h),
    ae_all_iff.2 (hasCondDistrib_IT_action h),
    ae_all_iff.2 (hasCondDistrib_IT_feedback h)] with _ hO hA hR
  exact ⟨IT.measurable_obs, IT.measurable_action, IT.measurable_feedback, hO, hA, hR⟩

end IsBayesAlgEnvSeq

section IsAlgEnvSeq

/-- An environment without observations whose feedback lies in `𝓔 × 𝓨`. The first element `e` of a
feedback is sampled from `Q` at time `0` and then remains constant: at time `n + 1` it is read from
the first round in the history. The second element of a feedback is sampled from `κ (e, a)`, where
`a` is the corresponding action. -/
noncomputable
def bayesStationaryEnv (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] : Environment Unit 𝓐 (𝓔 × 𝓨) where
  obs n := unitObs 𝓐 (𝓔 × 𝓨) n
  feedback
    | 0 => ((Kernel.const _ Q) ⊗ₖ κ.swapLeft).prodMkLeft _
    | n + 1 =>
      let g : (Hist Unit 𝓐 (𝓔 × 𝓨) (n + 1) × Unit) × 𝓐 → 𝓔 × 𝓐 :=
        fun p ↦ ((p.1.1 0).feedback.1, p.2)
      (Kernel.deterministic (Prod.fst ∘ g) (by fun_prop)) ×ₖ (κ.comap g (by fun_prop))
  isMarkovKernel_feedback n := by cases n <;> infer_instance

variable {Q : Measure 𝓔} [IsProbabilityMeasure Q] {κ : Kernel (𝓔 × 𝓐) 𝓨} [IsMarkovKernel κ]

@[simp]
lemma bayesStationaryEnv_obs (n : ℕ) :
    (bayesStationaryEnv Q κ).obs n = unitObs 𝓐 (𝓔 × 𝓨) n := rfl

lemma bayesStationaryEnv_feedback_zero :
    (bayesStationaryEnv Q κ).feedback 0 = ((Kernel.const _ Q) ⊗ₖ κ.swapLeft).prodMkLeft _ := rfl

lemma bayesStationaryEnv_feedback_succ (n : ℕ) :
    (bayesStationaryEnv Q κ).feedback (n + 1) =
      (Kernel.deterministic (Prod.fst ∘ (fun p : (Hist Unit 𝓐 (𝓔 × 𝓨) (n + 1) × Unit) × 𝓐 ↦
        ((p.1.1 0).feedback.1, p.2))) (by fun_prop)) ×ₖ
        (κ.comap (fun p ↦ ((p.1.1 0).feedback.1, p.2)) (by fun_prop)) := rfl

@[simp]
lemma ν0_bayesStationaryEnv :
    (bayesStationaryEnv Q κ).ν0 = ((Kernel.const _ Q) ⊗ₖ κ.swapLeft).prodMkLeft Unit := rfl

variable {alg : Algorithm Unit 𝓐 𝓨} {O : ℕ → Ω → Unit} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓔 × 𝓨}
variable {P : Measure Ω} [IsProbabilityMeasure P]

lemma IsAlgEnvSeq.isBayesAlgEnvSeq
    (h : IsAlgEnvSeq O A Y (alg.prodLeft 𝓔) (bayesStationaryEnv Q κ) P) :
    IsBayesAlgEnvSeq Q κ alg (fun ω ↦ (Y 0 ω).1) A (fun n ω ↦ (Y n ω).2) P where
  measurable_param := (h.measurable_feedback 0).fst
  measurable_action := h.measurable_action
  measurable_feedback n := (h.measurable_feedback n).snd
  hasLaw_env := by
    have hc : HasCondDistrib (Y 0) (A 0) ((Kernel.const _ Q) ⊗ₖ κ.swapLeft) P :=
      hasCondDistrib_prodMk_left_unique_iff.mp h.hasCondDistrib_feedback_zero
    have hc' : HasCondDistrib (fun ω ↦ (Y 0 ω).1) (A 0) (Kernel.const 𝓐 Q) P := by
      simpa [Kernel.fst_compProd] using hc.fst
    exact hc'.hasLaw_of_const
  hasCondDistrib_action n := by
    cases n with
    | zero =>
      -- At time `0` the history is empty: `E` is the parameter component of `Y 0`, which is
      -- independent of `A 0`.
      have hc0 : HasCondDistrib (Y 0) (A 0) ((Kernel.const _ Q) ⊗ₖ κ.swapLeft) P :=
        hasCondDistrib_prodMk_left_unique_iff.mp h.hasCondDistrib_feedback_zero
      have hc : HasCondDistrib (fun ω ↦ (Y 0 ω).1) (A 0) (Kernel.const _ Q) P := by
        simpa [Kernel.fst_compProd] using hc0.fst
      have h_law : HasLaw (A 0) (alg.p0 ()) P := by
        have h0 : HasCondDistrib (A 0) (fun _ : Ω ↦ ())
            ((alg.prodLeft 𝓔).p0) P := h.hasCondDistrib_action_zero
        simpa using h0.hasLaw_of_const'
      have hc' : HasCondDistrib (A 0) (fun ω ↦ (Y 0 ω).1) (Kernel.const _ (alg.p0 ())) P := by
        simpa [h_law.map_eq] using hc.const_map_of_const
      exact hasCondDistrib_prodMk_right_unique_iff.mpr hc'
    | succ n =>
      let f : (Hist Unit 𝓐 (𝓔 × 𝓨) (n + 1) × Unit) → 𝓔 × (Hist Unit 𝓐 𝓨 (n + 1) × Unit) :=
        fun p ↦ ((p.1 0).feedback.1,
          (fun i ↦ ((p.1 i).obs, (p.1 i).action, (p.1 i).feedback.2), p.2))
      have hc : HasCondDistrib (A (n + 1)) (fun ω ↦ (history O A Y (n + 1) ω, O (n + 1) ω))
          (((alg.policy (n + 1)).prodMkLeft 𝓔).comap f (by fun_prop)) P :=
        h.hasCondDistrib_action (n + 1)
      exact hc.comp_right (f := f)
  hasCondDistrib_feedback n := by
    cases n with
    | zero =>
      have hc : HasCondDistrib (Y 0) (A 0) ((Kernel.const _ Q) ⊗ₖ κ.swapLeft) P :=
        hasCondDistrib_prodMk_left_unique_iff.mp h.hasCondDistrib_feedback_zero
      exact hasCondDistrib_prodMk_left_unique_iff.mpr
        (hc.of_compProd.measurableEquiv_comp_right MeasurableEquiv.prodComm)
    | succ n =>
      let f : ((Hist Unit 𝓐 (𝓔 × 𝓨) (n + 1) × Unit) × 𝓐) →
          ((Hist Unit 𝓐 𝓨 (n + 1) × Unit) × 𝓔 × 𝓐) :=
        fun p ↦ ((fun i ↦ ((p.1.1 i).obs, (p.1.1 i).action, (p.1.1 i).feedback.2), p.1.2),
          (p.1.1 0).feedback.1, p.2)
      have hc : HasCondDistrib (fun ω ↦ (Y (n + 1) ω).2)
          (fun ω ↦ ((history O A Y (n + 1) ω, O (n + 1) ω), A (n + 1) ω))
          ((Kernel.prodMkLeft (Hist Unit 𝓐 𝓨 (n + 1) × Unit) κ).comap f (by fun_prop)) P := by
        simpa [bayesStationaryEnv_feedback_succ, Kernel.prodMkLeft, ← Kernel.comap_comp_right,
          Function.comp_def] using (h.hasCondDistrib_feedback (n + 1)).snd
      exact hc.comp_right

end IsAlgEnvSeq

namespace IT

/-- A measure `P` on a measurable space that carries random variables `E`, `A`, and `Y` such that
`IsBayesAlgEnvSeq Q κ alg E A Y P`. -/
noncomputable
def bayesTrajMeasure (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨)
    [IsMarkovKernel κ] (alg : Algorithm Unit 𝓐 𝓨) : Measure (ℕ → Round Unit 𝓐 (𝓔 × 𝓨)) :=
  trajMeasure (alg.prodLeft 𝓔) (bayesStationaryEnv Q κ)
deriving IsProbabilityMeasure

lemma isBayesAlgEnvSeq_bayesTrajMeasure
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) :
    IsBayesAlgEnvSeq Q κ alg (fun ω ↦ (ω 0).feedback.1) action
      (fun n ω ↦ (ω n).feedback.2) (bayesTrajMeasure Q κ alg) :=
  (isAlgEnvSeq_trajMeasure _ _).isBayesAlgEnvSeq

/-- A kernel that represents the posterior over `E` given the history before time `n`. -/
noncomputable
def bayesTrajMeasurePosterior [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) (n : ℕ) : Kernel (Hist Unit 𝓐 𝓨 n) 𝓔 :=
  condDistrib (fun ω ↦ (ω 0).feedback.1)
    (history (noObs _) action (fun n ω ↦ (ω n).feedback.2) n)
    (bayesTrajMeasure Q κ alg)
deriving IsMarkovKernel

/-- The posterior given the empty history is the prior. -/
lemma bayesTrajMeasurePosterior_zero [StandardBorelSpace 𝓔] [Nonempty 𝓔]
    (Q : Measure 𝓔) [IsProbabilityMeasure Q] (κ : Kernel (𝓔 × 𝓐) 𝓨) [IsMarkovKernel κ]
    (alg : Algorithm Unit 𝓐 𝓨) :
    bayesTrajMeasurePosterior Q κ alg 0 = Kernel.const _ Q :=
  (isBayesAlgEnvSeq_bayesTrajMeasure Q κ alg).condDistrib_param_history_zero

end IT

end Learning
