/-
Copyright (c) 2025 Rémy Degenne. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Rémy Degenne, Paulo Rauber
-/
module

public import LeanMachineLearning.SequentialLearning.Algorithm

/-!
# Probability space for algorithm-environment interactions

For any algorithm and environment, we construct a probability space on which we can define
a sequence of random variables representing the actions and feedback generated by the interaction
of the algorithm and the environment.
The main ingredient of the construction is the Ionescu-Tulcea theorem.

## Main statements

* `isAlgEnvSeq_unique`: the law of the sequence of actions and observations generated by an
  algorithm-environment pair is unique: it does not depend on the probability space used.
  If `A₁`, `R₁` and `A₂`, `R₂` are two algorithm-environment sequences generated by the same
  algorithm-environment pair on probability spaces `(Ω, P)` and `(Ω', P')`, then
  `P.map (fun ω n ↦ (A₁ n ω, R₁ n ω)) = P'.map (fun ω n ↦ (A₂ n ω, R₂ n ω))`.

-/

@[expose] public section

open MeasureTheory ProbabilityTheory Filter Real Finset

open scoped ENNReal NNReal

namespace Learning

variable {𝓐 𝓨 Ω : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- Measure on the sequence of actions and observations generated by the algorithm/environment. -/
noncomputable
def trajMeasure (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    Measure (ℕ → 𝓐 × 𝓨) :=
  Kernel.trajMeasureFin (stepKernel alg env)
deriving IsProbabilityMeasure

namespace IT

/-- Action and feedback at step `n`. -/
def step (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : 𝓐 × 𝓨 := h n

/-- `action n` is the action pulled at time `n`. This is a random variable on the measurable space
`ℕ → 𝓐 × 𝓨`. -/
def action (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : 𝓐 := (h n).1

/-- `feedback n` is the feedback at time `n`. This is a random variable on the measurable space
`ℕ → 𝓐 × 𝓨`. -/
def feedback (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : 𝓨 := (h n).2

/-- `hist n` is the history before time `n`: the action-feedback pairs at times `0, ..., n - 1`.
This is a random variable on the measurable space `ℕ → 𝓐 × 𝓨`. -/
def hist (n : ℕ) (h : ℕ → 𝓐 × 𝓨) : Fin n → 𝓐 × 𝓨 := fun i ↦ h i

lemma fst_comp_step (n : ℕ) : Prod.fst ∘ step (𝓐 := 𝓐) (𝓨 := 𝓨) n = action n := rfl

lemma history_action_feedback (n : ℕ) :
    history (action (𝓐 := 𝓐) (𝓨 := 𝓨)) feedback n = hist n := rfl

@[simp]
lemma hist_zero : hist (𝓐 := 𝓐) (𝓨 := 𝓨) 0 = fun _ ↦ default := Unique.eq_default _

@[fun_prop]
lemma measurable_step (n : ℕ) : Measurable (step n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold step; fun_prop

@[fun_prop]
lemma measurable_step_prod : Measurable (fun p : ℕ × (ℕ → 𝓐 × 𝓨) ↦ step p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_action (n : ℕ) : Measurable (action n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold action; fun_prop

@[fun_prop]
lemma measurable_action_prod : Measurable (fun p : ℕ × (ℕ → 𝓐 × 𝓨) ↦ action p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_feedback (n : ℕ) : Measurable (feedback n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  unfold feedback; fun_prop

@[fun_prop]
lemma measurable_feedback_prod : Measurable (fun p : ℕ × (ℕ → 𝓐 × 𝓨) ↦ feedback p.1 p.2) :=
  measurable_from_prod_countable_right fun n ↦ (by simp only; fun_prop)

@[fun_prop]
lemma measurable_hist (n : ℕ) : Measurable (hist n (𝓐 := 𝓐) (𝓨 := 𝓨)) := by unfold hist; fun_prop

lemma hist_succ_eq_comp_frestrictLe (n : ℕ) :
    hist (𝓐 := 𝓐) (𝓨 := 𝓨) (n + 1) =
      (MeasurableEquiv.finSuccPiIic (fun _ ↦ 𝓐 × 𝓨) n).symm ∘ Preorder.frestrictLe n := rfl

lemma frestrictLe_eq_comp_hist (n : ℕ) :
    Preorder.frestrictLe («π» := fun _ ↦ 𝓐 × 𝓨) n =
      (MeasurableEquiv.finSuccPiIic (fun _ ↦ 𝓐 × 𝓨) n) ∘ hist (n + 1) := rfl

lemma step_eq_eval_comp_hist (n : ℕ) :
    step (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ x (Fin.last n)) ∘ (hist (n + 1)) := rfl

lemma action_eq_eval_comp_hist (n : ℕ) :
    action (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ (x (Fin.last n)).1) ∘ (hist (n + 1)) := rfl

lemma feedback_eq_eval_comp_hist (n : ℕ) :
    feedback (𝓐 := 𝓐) (𝓨 := 𝓨) n = (fun x ↦ (x (Fin.last n)).2) ∘ (hist (n + 1)) := rfl

/-- The history before time `m` is a restriction of the history before time `n ≥ m`. -/
lemma hist_eq_comp_hist {m n : ℕ} (hmn : m ≤ n) :
    hist (𝓐 := 𝓐) (𝓨 := 𝓨) m = (fun h (i : Fin m) ↦ h (Fin.castLE hmn i)) ∘ hist n := rfl

end IT

section ModelEquivalence

variable {Ω Ω' : Type*} {mΩ : MeasurableSpace Ω} {mΩ' : MeasurableSpace Ω'}
  {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨}
  {P : Measure Ω} [IsProbabilityMeasure P] {P' : Measure Ω'} [IsProbabilityMeasure P']
  {A₁ : ℕ → Ω → 𝓐} {R₁ : ℕ → Ω → 𝓨} {A₂ : ℕ → Ω' → 𝓐} {R₂ : ℕ → Ω' → 𝓨} {N : ℕ}

lemma IsAlgEnvSeq.map_trajectory (h : IsAlgEnvSeq A₁ R₁ alg env P) :
    P.map (trajectory A₁ R₁) = trajMeasure alg env :=
  (Kernel.hasLaw_trajMeasureFin (X := fun _ ↦ 𝓐 × 𝓨) (Y := step A₁ R₁) (P := P)
    (κ' := stepKernel alg env) h.measurable_step h.hasCondDistrib_step).map_eq

lemma IsAlgEnvSeq.hasLaw_trajectory (h : IsAlgEnvSeq A₁ R₁ alg env P) :
    HasLaw (trajectory A₁ R₁) (trajMeasure alg env) P where
  aemeasurable := h.measurable_trajectory.aemeasurable
  map_eq := h.map_trajectory

lemma IsAlgEnvSeqUntil.map_history (h : IsAlgEnvSeqUntil A₁ R₁ alg env P N) :
    P.map (history A₁ R₁ N) = (trajMeasure alg env).map (IT.hist N) :=
  Kernel.eq_trajMeasureFin_map (X := fun _ ↦ 𝓐 × 𝓨) (Y := step A₁ R₁) (P := P) (N := N)
    (κ' := stepKernel alg env) h.measurable_step h.hasCondDistrib_step

lemma IsAlgEnvSeq.map_history (h : IsAlgEnvSeq A₁ R₁ alg env P) (n : ℕ) :
    P.map (history A₁ R₁ n) = (trajMeasure alg env).map (IT.hist n) :=
  (h.isAlgEnvSeqUntil n).map_history

/-- The law of the sequence of actions and observations generated by an algorithm-environment pair
is unique: it does not depend on the probability space used. -/
lemma isAlgEnvSeq_unique (h1 : IsAlgEnvSeq A₁ R₁ alg env P)
    (h2 : IsAlgEnvSeq A₂ R₂ alg env P') :
    P.map (trajectory A₁ R₁) = P'.map (trajectory A₂ R₂) := by
  rw [h1.map_trajectory, h2.map_trajectory]

/-- The law of the sequence of actions and observations generated by an algorithm-environment pair
is unique: it does not depend on the probability space used. -/
theorem IsAlgEnvSeq.identDistrib_trajectory (h1 : IsAlgEnvSeq A₁ R₁ alg env P)
    (h2 : IsAlgEnvSeq A₂ R₂ alg env P') :
    IdentDistrib (trajectory A₁ R₁) (trajectory A₂ R₂) P P' where
  aemeasurable_fst := h1.measurable_trajectory.aemeasurable
  aemeasurable_snd := h2.measurable_trajectory.aemeasurable
  map_eq := isAlgEnvSeq_unique h1 h2

/-- The law of the history before time `N` is determined by the algorithm-environment pair,
provided that the sequence is an algorithm-environment sequence until time `N`. -/
lemma isAlgEnvSeqUntil_unique (h1 : IsAlgEnvSeqUntil A₁ R₁ alg env P N)
    (h2 : IsAlgEnvSeqUntil A₂ R₂ alg env P' N) :
    P.map (history A₁ R₁ N) = P'.map (history A₂ R₂ N) := by
  rw [h1.map_history, h2.map_history]

end ModelEquivalence

namespace IT

/-- Filtration of the algorithm Seq: `IT.filtration 𝓐 𝓨 n` is the σ-algebra generated by the
action-feedback pairs at times `0, ..., n`, that is by `hist (n + 1)`. -/
protected def filtration (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → 𝓐 × 𝓨)) :=
  MeasureTheory.Filtration.piLE (X := fun _ ↦ 𝓐 × 𝓨)

lemma filtration_eq_comap (n : ℕ) :
    IT.filtration 𝓐 𝓨 n = MeasurableSpace.comap (hist (n + 1)) inferInstance := by
  simp only [IT.filtration, Filtration.piLE_eq_comap_frestrictLe]
  refine le_antisymm ?_ ?_
  · rw [← measurable_iff_comap_le, frestrictLe_eq_comp_hist]
    exact measurable_comp_comap _ (by fun_prop)
  · rw [← measurable_iff_comap_le, hist_succ_eq_comp_frestrictLe]
    exact measurable_comp_comap _ (by fun_prop)

lemma adapted_step : Adapted (IT.filtration 𝓐 𝓨) (step (𝓐 := 𝓐) (𝓨 := 𝓨)) := by
  intro n
  rw [filtration_eq_comap, step_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma measurable_hist_succ_filtration (n : ℕ) :
    Measurable[IT.filtration 𝓐 𝓨 n] (hist (n + 1)) := by
  rw [filtration_eq_comap]
  exact measurable_iff_comap_le.mpr le_rfl

lemma adapted_hist : Adapted (IT.filtration 𝓐 𝓨) hist := by
  intro n
  rw [filtration_eq_comap, hist_eq_comp_hist n.le_succ]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_action : Adapted (IT.filtration 𝓐 𝓨) action := by
  intro n
  rw [filtration_eq_comap, action_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

lemma adapted_feedback : Adapted (IT.filtration 𝓐 𝓨) feedback := by
  intro n
  rw [filtration_eq_comap, feedback_eq_eval_comp_hist]
  exact measurable_comp_comap _ (by fun_prop)

section FiltrationAction

/-- Filtration generated by the history before time `n` together with the action at time `n`. -/
def filtrationAction (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] :
    Filtration ℕ (inferInstance : MeasurableSpace (ℕ → 𝓐 × 𝓨)) where
  seq n := MeasurableSpace.comap (fun ω ↦ (hist n ω, action n ω)) inferInstance
  mono' n m hnm := by
    simp only
    rw [← measurable_iff_comap_le]
    rcases eq_or_lt_of_le hnm with rfl | hlt
    · exact measurable_iff_comap_le.mpr le_rfl
    have : (fun ω ↦ (hist (𝓐 := 𝓐) (𝓨 := 𝓨) n ω, action n ω)) =
        (fun p : (Fin m → 𝓐 × 𝓨) × 𝓐 ↦
          (fun i : Fin n ↦ p.1 (Fin.castLE hnm i), (p.1 ⟨n, hlt⟩).1)) ∘
        (fun ω ↦ (hist m ω, action m ω)) := rfl
    rw [this]
    exact measurable_comp_comap _ (by fun_prop)
  le' n := by
    rw [← measurable_iff_comap_le]
    fun_prop

lemma filtrationAction_eq_comap (n : ℕ) :
    filtrationAction 𝓐 𝓨 n =
      MeasurableSpace.comap (fun ω ↦ (hist n ω, action n ω)) inferInstance := rfl

lemma filtrationAction_zero_eq_comap :
    filtrationAction 𝓐 𝓨 0 = MeasurableSpace.comap (action 0) inferInstance := by
  rw [filtrationAction_eq_comap, hist_zero]
  refine le_antisymm ?_ ?_
  · rw [← measurable_iff_comap_le]
    exact measurable_const.prodMk (measurable_iff_comap_le.mpr le_rfl)
  · rw [← measurable_iff_comap_le]
    exact measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl)

lemma measurable_hist_filtrationAction (n : ℕ) :
    Measurable[filtrationAction 𝓐 𝓨 n] (hist n) :=
  measurable_fst.comp (measurable_iff_comap_le.mpr le_rfl)

lemma filtration_le_filtrationAction_add_one (n : ℕ) :
    IT.filtration 𝓐 𝓨 n ≤ filtrationAction 𝓐 𝓨 (n + 1) := by
  rw [filtration_eq_comap]
  exact measurable_iff_comap_le.mp (measurable_hist_filtrationAction (n + 1))

lemma filtration_le_filtrationAction {m n : ℕ} (h : n < m) :
    IT.filtration 𝓐 𝓨 n ≤ filtrationAction 𝓐 𝓨 m := by
  have h' : n + 1 ≤ m := by grind
  exact (filtration_le_filtrationAction_add_one n).trans ((filtrationAction 𝓐 𝓨).mono h')

lemma filtrationAction_le_filtration_self (n : ℕ) :
    filtrationAction 𝓐 𝓨 n ≤ IT.filtration 𝓐 𝓨 n := by
  rw [filtrationAction_eq_comap, ← measurable_iff_comap_le]
  exact (adapted_hist n).prodMk (adapted_action n)

lemma filtrationAction_le_filtration {m n : ℕ} (h : m ≤ n) :
    filtrationAction 𝓐 𝓨 m ≤ IT.filtration 𝓐 𝓨 n :=
  (filtrationAction_le_filtration_self m).trans ((IT.filtration 𝓐 𝓨).mono h)

lemma measurable_action_filtrationAction (n : ℕ) :
    Measurable[filtrationAction 𝓐 𝓨 n] (action n) :=
  measurable_snd.comp (measurable_iff_comap_le.mpr le_rfl)

end FiltrationAction

section Laws

lemma hasCondDistrib_step (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (step n) (hist n) (stepKernel alg env n) (trajMeasure alg env) :=
  Kernel.hasCondDistrib_trajMeasureFin n

lemma hasCondDistrib_action (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (action n) (hist n) (alg.policy n) (trajMeasure alg env) := by
  rw [← fst_comp_step, ← fst_stepKernel, Kernel.fst_eq]
  exact HasCondDistrib.comp_left (hasCondDistrib_step alg env n) measurable_fst

lemma hasCondDistrib_feedback (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    HasCondDistrib (feedback n) (fun ω ↦ (hist n ω, action n ω)) (env.feedback n)
      (trajMeasure alg env) := by
  have h_step := hasCondDistrib_step alg env n
  have h_action := hasCondDistrib_action alg env n
  refine ⟨by fun_prop, ?_⟩
  rw [h_action.map_eq, ← Measure.compProd_assoc, ← stepKernel, ← h_step.map_eq,
    Measure.map_map (by fun_prop) (by fun_prop)]
  rfl

lemma isAlgEnvSeq_trajMeasure (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    IsAlgEnvSeq action feedback alg env (trajMeasure alg env) where
  hasCondDistrib_action n := hasCondDistrib_action alg env n
  hasCondDistrib_feedback n := hasCondDistrib_feedback alg env n

lemma hasLaw_step_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    HasLaw (step 0) (alg.p0 ⊗ₘ env.ν0) (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasLaw_step_zero

lemma hasLaw_action_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    HasLaw (action 0) alg.p0 (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasLaw_action_zero

lemma hasCondDistrib_feedback_zero (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    HasCondDistrib (feedback 0) (action 0) env.ν0 (trajMeasure alg env) :=
  (isAlgEnvSeq_trajMeasure alg env).hasCondDistrib_feedback_zero

lemma condDistrib_feedback_zero [StandardBorelSpace 𝓨] [Nonempty 𝓨]
    (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) :
    condDistrib (feedback 0) (action 0) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (action 0)] env.ν0 :=
  (hasCondDistrib_feedback_zero alg env).condDistrib_eq

lemma condDistrib_step [StandardBorelSpace 𝓐] [Nonempty 𝓐] [StandardBorelSpace 𝓨] [Nonempty 𝓨]
    (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    condDistrib (step n) (hist n) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (hist n)] stepKernel alg env n :=
  (hasCondDistrib_step alg env n).condDistrib_eq

lemma condDistrib_action [StandardBorelSpace 𝓐] [Nonempty 𝓐]
    (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    condDistrib (action n) (hist n) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (hist n)] alg.policy n :=
  (hasCondDistrib_action alg env n).condDistrib_eq

lemma condDistrib_feedback [StandardBorelSpace 𝓨] [Nonempty 𝓨]
    (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨) (n : ℕ) :
    condDistrib (feedback n) (fun ω ↦ (hist n ω, action n ω)) (trajMeasure alg env)
      =ᵐ[(trajMeasure alg env).map (fun ω ↦ (hist n ω, action n ω))] env.feedback n :=
  (hasCondDistrib_feedback alg env n).condDistrib_eq

end Laws

end IT

end Learning
