name = "LeanMachineLearning"
defaultTargets = ["LeanMachineLearning"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.35.0-rc3"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "1f414401f69059aa7eead47b53ee40bd38455eeb"

[[lean_lib]]
name = "LeanMachineLearning"

[[lean_lib]]
name = "LMLTutorial"
globs = ["LMLTutorial.*"]

[[lean_exe]]
name = "tutorial"
srcDir = "LMLTutorial/"
root = "Tutorial"
