name = "LeanMachineLearning"
defaultTargets = ["LeanMachineLearning"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "b2b425516745501699f012f5a96fb50a826b3281"

[[lean_lib]]
name = "LeanMachineLearning"

[[lean_lib]]
name = "LMLTutorial"
globs = ["LMLTutorial.*"]

[[lean_exe]]
name = "tutorial"
srcDir = "LMLTutorial/"
root = "Tutorial"
