/-
Copyright (c) 2026 Yi Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yi Yuan
-/
module

public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.Topology.ContinuousMap.StoneWeierstrass

/-!
# Density of polynomials in inner-product coordinates

The linear coordinate functions given by an inner product separate points. Consequently, on a
compact subtype, the algebra that they generate is dense in the continuous real-valued functions.
-/

@[expose] public section

namespace ContinuousMap

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- The real inner-product coordinate `x ↦ ⟪w, x⟫` on a subtype. -/
def innerProductCoordinate (K : Set E) (w : E) : C(K, ℝ) :=
  ⟨fun x ↦ inner ℝ w x.1, continuous_const.inner continuous_subtype_val⟩

@[simp]
theorem innerProductCoordinate_apply (K : Set E) (w : E) (x : K) :
    innerProductCoordinate K w x = inner ℝ w x.1 := rfl

/-- The algebra generated by the real inner-product coordinates on a subtype separates points.

No compactness or finite-dimensionality assumption is needed for this fact.
-/
theorem innerProduct_adjoin_separatesPoints (K : Set E) :
    (Algebra.adjoin ℝ (Set.range (innerProductCoordinate K))).SeparatesPoints := by
  intro x y hxy
  let w : E := x.1 - y.1
  let f : C(K, ℝ) := innerProductCoordinate K w
  refine ⟨f, ?_, ?_⟩
  · exact ⟨f, ⟨Algebra.subset_adjoin ⟨w, rfl⟩, rfl⟩⟩
  · intro h
    apply hxy
    apply Subtype.ext
    apply sub_eq_zero.mp
    apply (inner_self_eq_zero.mp : inner ℝ w w = 0 → w = 0)
    rw [inner_sub_right]
    exact sub_eq_zero.mpr h

/-- On a compact subtype of a real inner-product space, the closure of the algebra generated by
the inner-product coordinates is the full algebra of continuous real-valued functions. -/
theorem innerProduct_adjoin_topologicalClosure_eq_top (K : Set E) [CompactSpace K] :
    (Algebra.adjoin ℝ (Set.range (innerProductCoordinate K))).topologicalClosure = ⊤ :=
  subalgebra_topologicalClosure_eq_top_of_separatesPoints _
    (innerProduct_adjoin_separatesPoints K)

/-- On a compact subtype of a real inner-product space, the algebra generated by inner-product
coordinates is dense in the continuous real-valued functions. -/
theorem dense_innerProduct_adjoin (K : Set E) [CompactSpace K] :
    Dense (Algebra.adjoin ℝ (Set.range (innerProductCoordinate K)) : Set C(K, ℝ)) := by
  rw [dense_iff_closure_eq, ← Subalgebra.topologicalClosure_coe,
    innerProduct_adjoin_topologicalClosure_eq_top]
  rfl

end ContinuousMap
