/-
Copyright (c) 2026 Yi Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yi Yuan
-/
module

public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Topology.ContinuousMap.Algebra
public import Mathlib.Topology.ContinuousMap.Compact

/-!
# Single-hidden-layer neural networks

We define a neuron on a real inner product space and the vector space of finite-width shallow
networks generated by an activation function. Using `Submodule.span` means that finite linear
combinations and all their algebraic laws come from Mathlib's existing linear-algebra API.
-/

@[expose] public section

namespace Learning.ShallowNetwork

variable {E : Type*} [SeminormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- A single neuron with weight `w`, bias `b`, and activation `σ`. -/
def neuron (σ : C(ℝ, ℝ)) (w : E) (b : ℝ) : C(E, ℝ) :=
  σ.comp ⟨fun x ↦ inner ℝ w x + b, by fun_prop⟩

@[simp]
theorem neuron_apply (σ : C(ℝ, ℝ)) (w : E) (b : ℝ) (x : E) :
    neuron σ w b x = σ (inner ℝ w x + b) := rfl

/-- The restrictions to `K` of finite-width, single-hidden-layer networks with activation `σ`. -/
def spaceOn (σ : C(ℝ, ℝ)) (K : Set E) : Submodule ℝ C(K, ℝ) :=
  Submodule.span ℝ (Set.range fun p : E × ℝ ↦ (neuron σ p.1 p.2).restrict K)

end Learning.ShallowNetwork
