/-
Copyright (c) 2026 Yi Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yi Yuan
-/
module

public import Mathlib.Analysis.InnerProductSpace.Continuous
public import Mathlib.LinearAlgebra.Finsupp.LinearCombination
public import Mathlib.Topology.ContinuousMap.Algebra
public import Mathlib.Topology.ContinuousMap.Compact

/-!
# Single-hidden-layer neural networks

We define a neuron on a real inner product space and the vector space of finite-width shallow
networks generated by an activation function. Using `Submodule.span` means that finite linear
combinations and all their algebraic laws come from Mathlib's existing linear-algebra API.
-/

@[expose] public section

namespace Learning.ShallowNetwork

variable {E : Type*} [SeminormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- A single neuron with weight `w`, bias `b`, and activation `σ`. -/
def neuron (σ : C(ℝ, ℝ)) (w : E) (b : ℝ) : C(E, ℝ) :=
  σ.comp ⟨fun x ↦ inner ℝ w x + b, by fun_prop⟩

@[simp]
theorem neuron_apply (σ : C(ℝ, ℝ)) (w : E) (b : ℝ) (x : E) :
    neuron σ w b x = σ (inner ℝ w x + b) := rfl

/-- The real vector space of finite-width, single-hidden-layer networks with activation `σ`. -/
def space (σ : C(ℝ, ℝ)) : Submodule ℝ C(E, ℝ) :=
  Submodule.span ℝ (Set.range fun p : E × ℝ ↦ neuron σ p.1 p.2)

/-- The restrictions to `K` of finite-width, single-hidden-layer networks with activation `σ`. -/
def spaceOn (σ : C(ℝ, ℝ)) (K : Set E) : Submodule ℝ C(K, ℝ) :=
  Submodule.span ℝ (Set.range fun p : E × ℝ ↦ (neuron σ p.1 p.2).restrict K)

/-- Membership in `space` is exactly representability by a finite-width shallow network. -/
theorem mem_space_iff (σ : C(ℝ, ℝ)) (f : C(E, ℝ)) :
    f ∈ space σ ↔
      ∃ (m : ℕ) (a : Fin m → ℝ) (w : Fin m → E) (b : Fin m → ℝ),
        ∑ j, a j • neuron σ (w j) (b j) = f := by
  constructor
  · intro hf
    rw [space, Submodule.mem_span_set'] at hf
    obtain ⟨m, a, g, h⟩ := hf
    have hg : ∀ j, ∃ w b, neuron σ w b = (g j : C(E, ℝ)) := by
      intro j
      obtain ⟨p, hp⟩ := (g j).property
      exact ⟨p.1, p.2, hp⟩
    choose w b hb using hg
    exact ⟨m, a, w, b, by simpa only [← hb] using h⟩
  · rintro ⟨m, a, w, b, rfl⟩
    apply Submodule.sum_mem
    intro j hj
    apply Submodule.smul_mem
    exact Submodule.subset_span ⟨(w j, b j), rfl⟩

/-- Membership in `spaceOn` is exactly representability on `K` by a finite-width shallow
network. -/
theorem mem_spaceOn_iff (σ : C(ℝ, ℝ)) (K : Set E) (f : C(K, ℝ)) :
    f ∈ spaceOn σ K ↔
      ∃ (m : ℕ) (a : Fin m → ℝ) (w : Fin m → E) (b : Fin m → ℝ),
        ∑ j, a j • (neuron σ (w j) (b j)).restrict K = f := by
  constructor
  · intro hf
    rw [spaceOn, Submodule.mem_span_set'] at hf
    obtain ⟨m, a, g, h⟩ := hf
    have hg : ∀ j, ∃ w b, (neuron σ w b).restrict K = (g j : C(K, ℝ)) := by
      intro j
      obtain ⟨p, hp⟩ := (g j).property
      exact ⟨p.1, p.2, hp⟩
    choose w b hb using hg
    exact ⟨m, a, w, b, by simpa only [← hb] using h⟩
  · rintro ⟨m, a, w, b, rfl⟩
    apply Submodule.sum_mem
    intro j hj
    apply Submodule.smul_mem
    exact Submodule.subset_span ⟨(w j, b j), rfl⟩

/-- `spaceOn` is the image of the global network space under restriction. -/
theorem spaceOn_eq_map (σ : C(ℝ, ℝ)) (K : Set E) :
    spaceOn σ K = (space σ).map
      (ContinuousMap.compCLM ℝ ℝ ⟨((↑) : K → E), continuous_subtype_val⟩).toLinearMap := by
  rw [spaceOn, space, Submodule.map_span]
  congr 1
  ext f
  aesop

variable (E) in
/-- An activation is universal on `E` if its shallow networks are dense on every compact
subset. This class packages the property for downstream approximation theorems. -/
class IsUniversal (σ : C(ℝ, ℝ)) : Prop where
  dense_on_compact : ∀ (K : Set E), IsCompact K → Dense (spaceOn σ K : Set C(K, ℝ))

/-- The typeclass formulation of universality unfolds to density on every compact subset. -/
theorem isUniversal_iff (σ : C(ℝ, ℝ)) :
    IsUniversal E σ ↔ ∀ (K : Set E), IsCompact K → Dense (spaceOn σ K : Set C(K, ℝ)) := by
  grind [IsUniversal]

/-- The usual uniform epsilon formulation of universal approximation on every compact set. -/
theorem isUniversal_iff_uniform_approximation (σ : C(ℝ, ℝ)) :
    IsUniversal E σ ↔
      ∀ (K : Set E), IsCompact K → ∀ (f : C(K, ℝ)) (ε : ℝ), 0 < ε →
        ∃ g ∈ spaceOn σ K, ∀ x, dist (g x) (f x) < ε := by
  constructor
  · rintro ⟨h⟩ K hK
    let _ : CompactSpace K := isCompact_iff_compactSpace.mp hK
    intro f ε hε
    obtain ⟨g, hgBall, hgSpace⟩ := Metric.dense_iff.mp (h K hK) f ε hε
    exact ⟨g, hgSpace, (ContinuousMap.dist_lt_iff hε).mp hgBall⟩
  · intro h
    constructor
    intro K hK
    let _ : CompactSpace K := isCompact_iff_compactSpace.mp hK
    rw [Metric.dense_iff]
    intro f ε hε
    obtain ⟨g, hgSpace, hgDist⟩ := h K hK f ε hε
    exact ⟨g, (ContinuousMap.dist_lt_iff hε).mpr hgDist, hgSpace⟩

end Learning.ShallowNetwork
