/-
Copyright (c) 2026 Yi Yuan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yi Yuan
-/
module

public import LeanMachineLearning.NeuralNetwork.UniversalApproximation.ConvolutionSmooth

/-!
# Nonpolynomial activations are discriminatory

This file assembles the analytic ingredients of the sufficient direction of the
Leshno--Lin--Pinkus--Schocken theorem.  Distributional differentiation supplies, at every order,
a compactly supported smooth convolution whose derivative is nonzero.  Annihilator transfer for
convolution and the smooth-ridge argument then imply that the original activation is
discriminatory.

The result applies to an arbitrary real inner-product space.  Finite dimensionality is not needed:
the approximation problem is posed on compact subsets, where the algebra generated by inner-product
coordinates still separates points.
-/

@[expose] public section

namespace Learning.ShallowNetwork

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]

/-- Every continuous nonpolynomial activation is discriminatory on compact subsets of an arbitrary
real inner-product space. -/
theorem isDiscriminatory_of_not_isPolynomial (σ : C(ℝ, ℝ))
    (hσ : ¬ Function.IsPolynomial σ) : IsDiscriminatory (E := E) σ := by
  apply HasContinuousDerivativeTower.isDiscriminatory_of_smooth_ridges σ
  intro n
  obtain ⟨φ, hφ⟩ :=
    exists_testFunction_derivative_convolutionActivation_ne_zero σ hσ n
  let g : C(ℝ, ℝ) := convolutionActivation φ σ
  let hg : HasContinuousDerivativeTower g := inferInstance
  refine ⟨g, hg, 0, ?_, ?_⟩
  · exact hφ
  · intro K hK Λ hΛ
    exact annihilates_convolutionActivation_neurons φ σ K hK Λ hΛ

end Learning.ShallowNetwork
